server:
  port: 8083

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: spacemannuclear@gmail.com
    password:

service:
  activation:
    uri: http://localhost:8086/user/activation?id={id}